version: '3.4'

services:
  pythontesseractalpine:
    image: samawi/python-weather-app-1
    build:
      context: backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - temp-images:/home/temp-images
      - web-images:/home/web-images

  fastapi:
    image: samawi/fastapi-weather-app-1
    build:
      context: fastapi
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    depends_on:
      - pythontesseractalpine
    volumes:
      - temp-images:/app/temp-images
      - web-images:/app/web-images

  react-app:
    image: samawi/react-weather-app
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - fastapi
    environment:
      - REACT_APP_API_URL=http://fastapi:8080
    volumes:
      - ./reactjs:/app
      - /app/node_modules
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped

volumes:
  web-images:
  temp-images:
